apiVersion: v1
kind: Service
metadata:
  name: kzozulya-pow-app-srv
spec:
  type: NodePort
  selector:
    app: kzozulya-pow-app
  ports:
    - name: custom-tcp
      targetPort: custom-tcp # container app port
      port: 8888 # srv port
      nodePort: 30007 # node entry point port